### ISSUE TITLE
Script missing

### ISSUE THREAD

**Issue by JYLeeBioinfo** [christopher-vollmers/AIRR-single-cell#1]
Hello!

I am trying to run the Ig and TCR analysis code in this repo but

it seems to fail because IGLWrapper_simple.py is not in the repo.

Could you help me with this?

Wrapper.py
![image](https://user-images.githubusercontent.com/13775022/109904063-01398f00-7ce0-11eb-816a-490c6b75384f.png)

**Comment by christopher-vollmers** [comment]
Just added the script. Sorry for the oversight. Let me know if you have any more issues!

**Comment by JYLeeBioinfo** [comment]
Thank you for your prompt reply!
I'll try the updated one

**Comment by hd00ljy** [comment]
Could I ask you about why you excluded some of IG and TR genes when you define regions for initial read filtering steps?

At the extracte4d sam file level,
I get high read counts for B cells at IGL,IGK,IGH regions (mostly >20)
but get very little read counts for T cells at TRA,TRB regions (mostly 0, 1~3 if any)

So I overlapped the regions with all the genes with gene type related to IMGT as described in GENCODE documentation (https://www.gencodegenes.org/pages/biotypes.html)
and found that some genes don't overlap the regions.

![image](https://user-images.githubusercontent.com/13775022/109928049-6012fe80-7d08-11eb-9769-74ba2fc74a5c.png)

I tried counting reads including those excluded genes but actually the read counts didn't dramatically increase

**Comment by christopher-vollmers** [comment]
Generally, T cells make less receptor transcripts than B cells. We talk
about that a little bit in the paper.
To be perfectly honest, I picked those boundaries by hand to contain the
loci as they appear on the genome browser. Quite possible I was a bit off
on the V segment ends of the loci.
Most important is that the boundaries contain the constant regions as those
are the only parts reads are more or less guaranteed to align.

**Comment by JYLeeBioinfo** [comment]
Thank you for your reply!

By the way, I accidentally deleted my original question, so I pasted that here

> Could I ask you about why you excluded some of IG and TR genes when you
> define regions for initial read filtering steps?
>
> At the extracte4d sam file level,
> I get high read counts for B cells at IGL,IGK,IGH regions (mostly >20)
> but get very little read counts for T cells at TRA,TRB regions (mostly 0,
> 1~3 if any)
>
> So I overlapped the regions with all the genes with gene type related to
> IMGT as described in GENCODE documentation (
> https://www.gencodegenes.org/pages/biotypes.html)
> and found that some genes don't overlap the regions.
>
> [image: image]
> <https://user-images.githubusercontent.com/13775022/109928049-6012fe80-7d08-11eb-9769-74ba2fc74a5c.png>
>
> I tried counting reads including those excluded genes but actually the
> read counts didn't dramatically increase
