### ISSUE TITLE
Cannot find TCRWrapper_updated.py

### ISSUE THREAD

**Issue by JYLeeBioinfo** [christopher-vollmers/AIRR-single-cell#2]
Hello!

I tried the recently updated version of the code.

I ran into an error that there is no file named TCRWrapper_updated.py

Could you share the TCRWrapper_updated.py script?

I am currently running the Wrapper.py after replacing TCRWrapper_updated.py with TCRWrapper_simple.py

With regards,
Jin-Young

**Comment by christopher-vollmers** [comment]
Turns out you are doing the correct thing. While I was updating this
workflow, I renamed the files to 'updated' but renamed back to 'simple'
them before I pushed them. Just forgot to also update one instance in the
Wrapper.py script.
I modified the wrapper script now.

Best,
Chrios

**Comment by JYLeeBioinfo** [comment]
Thank you for your reply!

Then it seems I can use the current results as it is

Thank you!
Jin-Young
